services:
  web:
    build: .
    command: gunicorn whatsapp_clone.wsgi:application --bind 127.0.0.1:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6380:6379"
